# project.yml
# Translatar - XcodeGen项目配置文件
#
# 使用方法：
# 1. 安装XcodeGen: brew install xcodegen
# 2. 在项目根目录运行: xcodegen generate
# 3. 打开生成的 Translatar.xcodeproj

name: Translatar

options:
  bundleIdPrefix: com.translatar
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"  # 仅iPhone
    INFOPLIST_FILE: Translatar/Info.plist
    MARKETING_VERSION: "3.0.0"
    CURRENT_PROJECT_VERSION: "3"
    DEVELOPMENT_TEAM: ""  # 请在Xcode中手动设置您的开发团队

targets:
  Translatar:
    type: application
    platform: iOS
    sources:
      - path: Translatar
        excludes:
          - Package.swift
          - Resources/Translatar.storekit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.translatar.app
        INFOPLIST_FILE: Translatar/Info.plist
    dependencies:
      - sdk: Speech.framework
      - sdk: AVFoundation.framework
      - sdk: Network.framework
      - sdk: StoreKit.framework
      - sdk: Translation.framework
        weak: true  # 弱链接，iOS 18以下不会崩溃
    entitlements:
      path: Translatar/Translatar.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
    scheme:
      testTargets: []
      storeKitConfiguration: Translatar/Resources/Translatar.storekit
